###Mutli Subscriptions
# {
#   "subjects" : [ "bs@simpsons.com", "ms@simpsons.com" ],
#   "actions" : [ "read" ],
#   "resources" : [ "file://example/med/record/patient/BartSimpson", "file://example/med/record/patient/MaggieSimpson" ],
#   "authorizationSubscriptions" : {
#     "id-2" : {
#       "subjectId" : 1,
#       "actionId" : 0,
#       "resourceId" : 1
#     },
#     "id-1" : {
#       "subjectId" : 0,
#       "actionId" : 0,
#       "resourceId" : 0
#     }
#   }
# }